### ISSUE TITLE
Tracking Issue GLTF I/O

### ISSUE THREAD

**Issue by benthillerkus** [mafo3186/venezia-website#49]
- [ ] https://github.com/pmndrs/gltfjsx/issues/277
  - [x] https://github.com/donmccurdy/glTF-Transform/issues/1505
- [x] https://github.com/pmndrs/gltfjsx/issues/276

Das hier ist nicht kritisch, wäre aber vielleicht ganz nett, um das GLTF etwas strukturierter zu haben / einfacher im Code zb ganze Gebäude auszublenden
- [x] https://github.com/KhronosGroup/glTF-Blender-IO/issues/2357

Wenn wir gltf-transform nicht nutzen (können) kann man (theoretisch) DRACO auch direkt in Blender laufen lassen. Das scheitert aber hieran:
- [ ] https://github.com/KhronosGroup/glTF-Blender-IO/issues/2184
  - [ ] https://github.com/KhronosGroup/glTF-Blender-IO/pull/2300
